'use client';
import { useState } from 'react';

type Source = { title: string; url: string };
type SqlModule = { id: string; level: string; title: string; summary: string; points: string[]; code: string; sources: Source[] };
type FileOp = { opcode: string; meaning: string; example: string; sql: string };
type Comparison = { rpg: string; sql: string; when: string; note: string; rpgLabel?: string; sqlLabel?: string };
type ErrorItem = { name: string; meaning: string; action: string };
type SqlCode = { code: string; state: string; outcome: string; meaning: string; when: string; action: string; example?: string };
type RpgSqlSection = { title: string; summary: string; code: string; points: string[] };
export type ReferenceData = { sqlModules: SqlModule[]; fileOps: FileOp[]; comparisons: Comparison[]; errors: ErrorItem[]; sqlCodes: SqlCode[]; rpgleGuide: RpgSqlSection[]; sources: Source[]; sqlCodeSources: Source[] };

function Sources({ sources }: { sources: Source[] }) {
  return <div className="reference-sources"><strong>Official references</strong>{sources.map((source) => <a key={source.url} href={source.url} target="_blank" rel="noreferrer">{source.title} ↗</a>)}</div>;
}

export function ReferenceHub({ data, tab = 'sql' }: { data: ReferenceData; tab?: string }) {
  const [active, setActive] = useState(tab === 'rpgle' || tab === 'files' || tab === 'compare' || tab === 'errors' || tab === 'codes' ? tab : 'sql');
  const change = (next: string) => {
    setActive(next);
    window.history.replaceState(null, '', `#sql-file-ops/${next}`);
    window.dispatchEvent(new HashChangeEvent('hashchange'));
  };
  return <article className="reference-hub">
    <div className="reference-hero"><span className="eyebrow">SQL + FILE OPERATIONS DESK</span><h2>Build the same data skill two ways.</h2><p>Learn Db2 for i from the first SELECT through transactions and performance, then use the RPG file operations that solve the same problems in native I/O.</p></div>
    <nav className="reference-tabs" aria-label="SQL and file operation guides">
      {[['sql', 'Db2 for i course'], ['rpgle', 'SQL in RPGLE'], ['files', 'RPG file opcodes'], ['compare', 'RPG ↔ SQL comparison'], ['errors', 'Error handling'], ['codes', 'SQL codes & SQLSTATE']].map(([id, label]) => <button key={id} className={active === id ? 'chosen' : ''} aria-pressed={active === id} onClick={() => change(id)}>{label}</button>)}
    </nav>
    {active === 'sql' && <section><div className="reference-intro"><h3>Db2 for i: beginner to advanced</h3><p>Move through the modules in order. Every example is a study skeleton: qualify names, parameterise values, check the result, and test it on your IBM i release.</p></div><div className="sql-module-grid">{data.sqlModules.map((module, index) => <details className="sql-module" key={module.id} open={index === 0}><summary aria-label={`Open ${module.title}`}><span className="reference-number">{String(index + 1).padStart(2, '0')}</span><span><strong>{module.title}</strong><small>{module.level} · {module.summary}</small></span></summary><div className="reference-answer"><ul>{module.points.map((point) => <li key={point}>{point}</li>)}</ul><pre><code>{module.code}</code></pre><Sources sources={module.sources} /></div></details>)}</div></section>}
    {active === 'rpgle' && <section><div className="reference-intro"><h3>Using SQL inside RPGLE programs</h3><p>Embedded SQL is a program lifecycle: set compile options, declare host variables, execute one-row or multi-row statements, inspect SQLSTATE and diagnostics, then commit or roll back deliberately.</p></div><nav className="reference-toc" aria-label="SQL in RPGLE contents"><strong>On this page</strong>{data.rpgleGuide.map((module, index) => <a key={module.title} href={`#rpgle-${index + 1}`}>{String(index + 1).padStart(2, '0')} · {module.title}</a>)}</nav><div className="sql-module-grid">{data.rpgleGuide.map((module, index) => <details className="sql-module" id={`rpgle-${index + 1}`} key={module.title} open={index === 0}><summary aria-label={`Open ${module.title}`}><span className="reference-number">{String(index + 1).padStart(2, '0')}</span><span><strong>{module.title}</strong><small>{module.summary}</small></span></summary><div className="reference-answer"><ul>{module.points.map((point) => <li key={point}>{point}</li>)}</ul><pre><code>{module.code}</code></pre></div></details>)}</div><Sources sources={data.sources.slice(0, 4)} /></section>}
    {active === 'files' && <section><div className="reference-intro"><h3>RPG file operation codebook</h3><p>Use this as a one-page lookup. The SQL column is a conceptual equivalent, not a promise that the two operations have identical locking, cursor, or error behavior.</p></div><div className="opcode-table-wrap"><table className="opcode-table"><thead><tr><th>Opcode</th><th>One-line definition</th><th>RPG example</th><th>SQL idea</th></tr></thead><tbody>{data.fileOps.map((item) => <tr key={item.opcode}><th scope="row"><code>{item.opcode}</code></th><td>{item.meaning}</td><td><pre aria-label={`${item.opcode} RPG example`}><code>{item.example}</code></pre></td><td><pre aria-label={`${item.opcode} SQL idea`}><code>{item.sql}</code></pre></td></tr>)}</tbody></table></div><Sources sources={data.sources.slice(0, 3)} /></section>}
    {active === 'compare' && <section><div className="reference-intro"><h3>RPG I/O and embedded SQL side by side</h3><p>Start with the intent, then choose the interface that fits the application. The detailed cards use fully free RPGLE on both sides. Pay attention to ordering, not-found behavior, locks, nulls, and affected-row counts.</p></div><div className="comparison-list">{data.comparisons.map((item) => <article key={item.rpg} className="comparison-card"><div className="comparison-heading"><strong>{item.when}</strong><span>Intent</span></div><div className="comparison-code"><div><small>{item.rpgLabel || 'RPG operation'}</small><pre><code>{item.rpg}</code></pre></div><div><small>{item.sqlLabel || 'SQL pattern'}</small><pre><code>{item.sql}</code></pre></div></div><p>{item.note}</p></article>)}</div><Sources sources={data.sources.slice(0, 3)} /></section>}
    {active === 'errors' && <section><div className="reference-intro"><h3>Common SQL and file-operation errors</h3><p>Use the symptom to choose evidence first. Preserve the original diagnostic and verify the final behavior with a normal case, a boundary case, and a failure case.</p></div><div className="error-grid">{data.errors.map((item) => <details className="error-card" key={item.name}><summary aria-label={`Open error guidance for ${item.name}`}><code>{item.name}</code><span>{item.meaning}</span></summary><div><strong>What to do next</strong><p>{item.action}</p></div></details>)}</div><Sources sources={data.sources.slice(0, 3)} /></section>}
    {active === 'codes' && <section><div className="reference-intro"><h3>Common SQLCODEs and SQLSTATEs</h3><p>Read the result after every SQL statement. SQLCODE is useful on IBM i, while SQLSTATE gives a five-character condition that is easier to standardise across Db2 products.</p></div><div className="sql-code-summary"><article><strong>0 · 00000</strong><span>Success</span><p>Statement completed without an error or exceptional condition.</p></article><article><strong>+100 · 02000</strong><span>Warning / no data</span><p>Expected boundary such as no matching row or cursor end.</p></article><article><strong>Negative code</strong><span>Failure</span><p>Statement did not complete; preserve diagnostics before recovery.</p></article></div><div className="sql-code-grid">{data.sqlCodes.map((item) => <details className={`sql-code-card ${item.outcome.toLowerCase().replace(/[^a-z]+/g, '-')}`} key={`${item.code}-${item.state}`}><summary><span className="sql-code-badge">{item.code}</span><span><strong>{item.meaning}</strong><small>SQLSTATE {item.state} · {item.outcome}</small></span></summary><div className="reference-answer"><p><strong>Typical trigger:</strong> {item.when}</p><p><strong>Response:</strong> {item.action}</p>{item.example && <pre><code>{item.example}</code></pre>}</div></details>)}</div><div className="sql-code-pattern"><h4>A safe RPGLE decision pattern</h4><pre><code>{'exec sql\\n  select NAME into :customerName\\n    from MYLIB.CUSTOMER\\n   where CUSTOMER_ID = :customerId;\\n\\nselect;\\nwhen SQLSTATE = \'00000\';\\n  // use the result\\nwhen SQLSTATE = \'02000\';\\n  // expected no-row branch\\nother;\\n  // log SQLCODE, SQLSTATE, and message details\\nendsl;'}</code></pre><p>For multi-row work, handle SQLSTATE <code>02000</code> as the cursor end condition. For a failure, capture the message text and relevant diagnostics before deciding whether to roll back, retry, or return an error.</p></div><Sources sources={data.sqlCodeSources} /></section>}
    <p className="reference-disclaimer">Examples are for learning and interview preparation. Verify syntax, release behavior, authority, journaling, locking, and deployment steps against current IBM documentation and a development partition before implementation.</p>
  </article>;
}
